Repository nimblehq/rails-view-component-blog, pull requests merged in 2021-09, with the labels that each got.

#19 [Task-2][Chore] Setup Heroku deployment
  .github/workflows/deploy_heroku.yml
  db/schema.rb
Labels: type : chore, backend

#22 [Task-8][Backend] As a user I can CRUD Article
  .rubocop.yml
  .scss-lint.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/vendor/actiontext/actiontext.scss
  app/assets/stylesheets/vendor/trix/trix.scss
  app/controllers/articles_controller.rb
  app/javascript/packs/application.js
  app/models/article.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/articles/_form.html.erb
  app/views/articles/edit.html.erb
  app/views/articles/index.html.erb
  app/views/articles/new.html.erb
  app/views/articles/show.html.erb
  config/routes.rb
  db/migrate/20210921054803_create_articles.rb
  db/migrate/20210921055511_create_active_storage_tables.active_storage.rb
  db/migrate/20210921055606_create_action_text_tables.action_text.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: type : feature, backend

#20 [Task-3][Chore] Configure view_component and view_component_storybook
  .github/workflows/deploy_heroku.yml
  .gitignore
  .rubocop.yml
  .storybook/main.js
  .storybook/preview.js
  Gemfile
  Gemfile.lock
  README.md
  app/components/button_component.html.erb
  app/components/button_component.rb
  app/controllers/concerns/.keep
  app/controllers/posts_controller.rb
  app/views/posts/index.html.erb
  config/application.rb
  config/routes.rb
  package.json
  public/_storybook/0.4fbd5f22c95b59c85e1c.manager.bundle.js
  public/_storybook/4.75d5a1b06644935772d5.manager.bundle.js
  public/_storybook/4.75d5a1b06644935772d5.manager.bundle.js.LICENSE.txt
  public/_storybook/5.698a0544e0b970e065db.manager.bundle.js
  public/_storybook/6.fd11e4fc27dcf8d83371.manager.bundle.js
  public/_storybook/6.fd11e4fc27dcf8d83371.manager.bundle.js.LICENSE.txt
  public/_storybook/7.8bbd0c97421a6b8bd315.manager.bundle.js
  public/_storybook/8.a4504e7cabb9b501b6b9.manager.bundle.js
  public/_storybook/favicon.ico
  public/_storybook/iframe.html
  public/_storybook/index.html
  public/_storybook/main.112c8004.iframe.bundle.js
  public/_storybook/main.2f3dafa3f7587a202de1.manager.bundle.js
  public/_storybook/runtime~main.31ad41dfc90584f62ce1.manager.bundle.js
  public/_storybook/runtime~main.77cb1220.iframe.bundle.js
  public/_storybook/vendors~main.087dfe1a.iframe.bundle.js
  public/_storybook/vendors~main.087dfe1a.iframe.bundle.js.LICENSE.txt
  public/_storybook/vendors~main.087dfe1a.iframe.bundle.js.map
  public/_storybook/vendors~main.f88355029a0cd94c38fe.manager.bundle.js
  public/_storybook/vendors~main.f88355029a0cd94c38fe.manager.bundle.js.LICENSE.txt
  spec/codebase/codebase_spec.rb
  spec/components/button_component_spec.rb
  spec/requests/.keep
  spec/requests/articles_controller_spec.rb
  spec/support/view_component.rb
  test/components/previews/button_component_preview.rb
  test/components/stories/button_component_stories.rb
  yarn.lock
Labels: type : chore

#25 Add stories for alerts
  test/components/previews/base/alert/component_preview.rb
  test/components/stories/base/alert/component_stories.rb
Labels: backend

#26 Add test to the alert and button components
  spec/components/base/alert/component_spec.rb
  spec/components/base/button/component_spec.rb
Labels: type : chore, backend
